services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - khaos_pg_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${RABBITMQ_NAME}
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    entrypoint: "/bin/sh -c 'sh /etc/rabbitmq/generate-definitions.sh && docker-entrypoint.sh rabbitmq-server'"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
      - ./rabbitmq/generate-definitions.sh:/etc/rabbitmq/generate-definitions.sh
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  khaos_pg_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
