CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE IF NOT EXISTS task_status AS ENUM ('PENDING', 'RUNNING','FINISHED','FAILED','CANCELLED');

CREATE TABLE IF NOT EXISTS tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  docker_process_id TEXT NOT NULL,
  status task_status DEFAULT 'PENDING',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );
