spring.application.name=execution-service
server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/khaos
spring.datasource.username=admin
spring.datasource.password=admin

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.separator=^^^ END OF SCRIPT ^^^

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

rabbitmq.topicExchangeName=code-exchange
rabbitmq.submittedQueueName=code-submitted
rabbitmq.executedQueueName=code-executed

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/khaos-dev
